import { useState, type FormEvent } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, CheckCircle2, Clock3, Copy, Github, LockKeyhole, MailCheck, MapPin, MessageCircle, ShieldCheck, Users } from "lucide-react";

const principles = [
  [Users, "How I engage", "Collaborations begin with a targeted technical discovery sprint: dissecting current bottlenecks, benchmarking latency surfaces, and establishing verifiable KPIs before a single line of architecture is deployed.", "Sprint-Based · Dedicated Advisory"],
  [CheckCircle2, "Code quality & testing standards", "Deterministic builds, rigorous fuzz testing, and continuous profiling. All deliverables integrate automated benchmark harnesses, zero-leak memory invariants, and thorough architectural documentation.", "Zero-Leak Standard · CI/CD Invariants"],
  [ShieldCheck, "NDA & IP ownership", "Full client IP assignment on completion. Standard bilateral NDA execution prior to proprietary system inspection. No vendor lock-in or obfuscated libraries ever introduced into your codebase.", "100% Client IP · Clean Handover"],
] as const;

export const Route = createFileRoute("/inquiries")({
  head: () => ({ meta: [
    { title: "Zakary / Zaknx — Project Inquiries & Consulting" },
    { name: "description", content: "Send a project enquiry for systems architecture, deep learning infrastructure, or technical advisory work." },
    { property: "og:title", content: "Zakary / Zaknx — Project Inquiries & Consulting" },
    { property: "og:description", content: "Architectural consultation for high-throughput systems, neural infrastructure, and distributed products." },
    { property: "og:type", content: "website" },
    { name: "twitter:card", content: "summary_large_image" },
  ] }),
  component: InquiriesPage,
});

function InquiriesPage(){
  const [sent,setSent]=useState(false); const [copied,setCopied]=useState(false);
  function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setSent(true);}
  async function copyEmail(){try{await navigator.clipboard.writeText("zakary.eng@dev.io");setCopied(true);window.setTimeout(()=>setCopied(false),1800);}catch{setCopied(false)}}
  return <div className="min-h-screen bg-background text-foreground">
    <header className="sticky top-0 z-50 bg-surface/90 backdrop-blur-md"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-5 md:px-12"><Link to="/" className="font-headline text-lg font-bold">Zakary / Zaknx</Link><nav className="hidden items-center gap-8 md:flex" aria-label="Primary navigation"><Link to="/work" className="nav-link">Selected Work</Link><Link to="/engineering" className="nav-link">Engineering</Link><Link to="/" hash="bio" className="nav-link">Curator Bio</Link><Link to="/inquiries" className="nav-link active">Inquiries</Link></nav><span className="hidden items-center rounded-full bg-surface-high px-3 py-1.5 font-label text-xs font-semibold uppercase text-tertiary sm:inline-flex"><span className="mr-2 h-1.5 w-1.5 animate-pulse rounded-full bg-primary"/> Available for Q3 '24</span></div></header>
    <main>
      <section className="mx-auto max-w-7xl px-6 pb-14 pt-16 md:px-12 md:pt-24"><div className="label mb-7 flex flex-wrap gap-3"><span className="font-bold text-primary">Status</span><span className="text-outline">·</span><span>Available for Q3/Q4 engagements</span><span className="text-outline">·</span><span>Remote / Worldwide</span></div><h1 className="font-headline text-4xl font-semibold md:text-6xl">Send Project Enquiries</h1><p className="mt-6 max-w-3xl text-lg leading-relaxed text-surface-variant md:text-xl">Available for high-impact systems architecture, deep learning infrastructure, and select technical advisory roles.</p><div className="mt-10 grid gap-4 border-y border-outline-subtle py-5 font-label text-xs uppercase text-surface-variant sm:grid-cols-3"><span>▣ &nbsp;High-Throughput & Low-Latency Systems</span><span>◷ &nbsp;Typical Response ≤ 24 Hours</span><span>✓ &nbsp;Mutual NDA Supported</span></div></section>
      <section className="bg-surface-low py-20"><div className="mx-auto grid max-w-7xl gap-8 px-6 lg:grid-cols-12 md:px-12"><div className="bg-surface p-7 shadow-card lg:col-span-7 md:p-10"><span className="label font-bold text-tertiary">Formal Dossier</span><p className="mt-1 font-mono text-xs text-outline">SEC-PROTOCOL // REQ-024</p><h2 className="mt-4 font-headline text-3xl font-semibold">Architectural Consultation Inquiry</h2><p className="mt-3 text-sm leading-relaxed text-surface-variant">Please furnish high-level technical parameters and workload requirements. All communications are strictly privileged.</p>
        <form onSubmit={submit} className="mt-8 space-y-6"><div className="grid gap-5 sm:grid-cols-2"><label className="form-field">Full Name <span>*</span><input required name="name" autoComplete="name"/></label><label className="form-field">Organization / Company <span>*</span><input required name="organization" autoComplete="organization"/></label></div><label className="form-field">Direct Email <span>*</span><input required type="email" name="email" autoComplete="email"/></label><label className="form-field">Project Scope <span>*</span><select required name="scope" defaultValue=""><option value="" disabled>Select Primary Focus</option><option>AI & Neural Systems</option><option>Low-Level C/C++ Architecture</option><option>Full-Stack Distributed Web</option><option>Technical Advisory / Consultation</option></select></label><label className="form-field">Estimated Timeline & Engagement Horizon<input name="timeline" placeholder="e.g. 8–12 weeks, beginning Q4"/></label><label className="form-field">Project Details & Architectural Requirements <span>*</span><textarea required name="details" rows={7}/><small>Markdown Supported</small></label><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><span className="flex items-center gap-2 text-xs text-outline"><LockKeyhole size={15}/>Encrypted via client-side SSL pipeline</span><button className="cta-primary" type="submit">Transmit Briefing <ArrowRight size={16}/></button></div>{sent&&<div role="status" className="flex gap-3 bg-surface-container p-4 text-sm text-surface-variant"><CheckCircle2 className="shrink-0 text-tertiary" size={19}/>Briefing received. Your architectural scope has been logged; a direct dispatch response will follow within 24 hours.</div>}</form></div>
        <aside className="space-y-6 lg:col-span-5"><div className="bg-surface p-7"><div className="flex items-center gap-3 text-primary"><MailCheck/><span className="label font-bold">Direct Transmission</span></div><h2 className="mt-5 font-headline text-2xl font-semibold">Electronic Mail</h2><p className="mt-2 text-sm text-surface-variant">For direct communication, PGP-encrypted dispatches, or institutional correspondence.</p><div className="mt-6 flex flex-wrap items-center justify-between gap-4 bg-surface-low p-4"><a className="font-mono text-sm font-semibold text-primary" href="mailto:zakary.eng@dev.io">zakary.eng@dev.io</a><button type="button" onClick={copyEmail} className="icon-link flex items-center gap-2 font-label text-xs uppercase" aria-label="Copy email"><Copy size={15}/>{copied?"Copied":"Copy"}</button></div><p className="mt-5 flex gap-2 text-xs text-surface-variant"><CheckCircle2 className="shrink-0 text-tertiary" size={15}/><span><strong>Response SLA:</strong> Typically replies within 24 hours for verified architectural enquiries.</span></p></div>
        <div className="bg-inverse-surface p-7 text-inverse-foreground"><span className="label text-code-keyword">Dispatches & Networks</span><div className="mt-5 divide-y divide-inverse-muted/20">{[{Icon:Github,name:"GitHub",value:"github.com/zaknx ↗",url:"https://github.com/zaknx"},{Icon:Users,name:"LinkedIn",value:"zakary-arch ↗",url:"#"},{Icon:MessageCircle,name:"Discord",value:"zaknx#0001 ↗",url:"#"},{Icon:MessageCircle,name:"Twitter / X",value:"@zaknx_sys ↗",url:"#"}].map(({Icon,name,value,url})=><a key={name} href={url} target={url==="#"?undefined:"_blank"} rel="noreferrer" className="flex items-center justify-between py-4 text-sm"><span className="flex items-center gap-3"><Icon size={17}/>{name}</span><span className="font-mono text-xs text-inverse-muted">{value}</span></a>)}</div></div>
        <div className="bg-surface-container p-7"><div className="flex items-center gap-3"><MapPin className="text-tertiary"/><div><span className="label text-outline">Base Coordinates</span><p className="mt-1 font-mono text-sm font-semibold">UTC+1 / CET</p></div></div><p className="mt-5 text-sm">Geneva · London · Remote Nodes</p><p className="mt-2 flex items-center gap-2 text-xs text-surface-variant"><Clock3 size={14}/>Infrastructure telemetry operating in nominal parameters.</p></div></aside></div></section>
      <section className="py-20"><div className="mx-auto max-w-7xl px-6 md:px-12"><span className="label font-bold text-primary">Engagement Protocol</span><h2 className="section-title mt-2">Working Principles & Governance</h2><p className="mt-3 max-w-3xl text-surface-variant">Rigorous engineering mandates clarity, predictable cadence, and unyielding ownership boundaries from day zero.</p><div className="mt-10 grid gap-6 md:grid-cols-3">{principles.map(([Icon,title,body,tag])=><article key={title} className="bg-surface p-7"><Icon className="text-primary" size={23}/><h3 className="mt-5 font-headline text-xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-relaxed text-surface-variant">{body}</p><p className="label mt-7 border-t border-outline-subtle pt-4 text-tertiary">{tag}</p></article>)}</div></div></section>
    </main><footer className="bg-surface-low"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-8 px-6 py-12 md:flex-row md:items-center md:px-12"><div><span className="font-headline text-xl font-bold italic">Zakary / Zaknx</span><p className="mt-2 text-sm text-surface-variant">© 2024 Zakary (Zaknx). Archival Folio. Designed with editorial rigor and algorithmic care.</p></div><nav className="flex flex-wrap gap-x-6 gap-y-3"><Link className="nav-link" to="/work" hash="project-c-lib">C_libery</Link><Link className="nav-link" to="/work" hash="project-ml">MachineLearning</Link><Link className="nav-link" to="/work" hash="project-studyflow">studyFlow</Link><Link className="nav-link" to="/work" hash="project-simulations">simulations-</Link></nav></div></footer>
  </div>
}